POST https://node-do-zero-j57f.onrender.com/videos
Content-Type: application/json

{
        "title": "Video 02",
        "description": "Esse é o video 01",
        "duration": "180"
}

###
GET https://node-do-zero-j57f.onrender.com/videos
###
PUT https://node-do-zero-j57f.onrender.com/videos/id
Content-Type: application/json

{
        "title": "Video 05",
        "description": "Esse é o video 05",
        "duration": "555"
}
###
DELETE https://node-do-zero-j57f.onrender.com/videos/3f7e87a0-998d-4e65-9126-ac8fc151cf24